version: '3'

services:

  web:
    container_name: jun_web
    build: ./docker
    ports:
      - 40:80
    privileged: true
    volumes:
      - /c/Users/oyama/test/jun/server:/var/www/html/public

  db:
    image: mysql:8.0
    container_name: jun_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 6640:3306

  phpmyadmin:
    container_name: jun_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=jun_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 6040:80

